name: Generate Pacman Contribution Animation

on:
  # Run automatically at 12 AM every day
  schedule:
    - cron: "0 0 * * *"
  
  # Allow manual triggering of the workflow
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out repository so the workflow can access it
      - uses: actions/checkout@v3
      
      # Setup Node.js environment
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      # Generate the Pacman animation SVG
      - name: Generate Pacman Animation
        run: |
          npm install @primer/octicons @actions/core @actions/github canvas d3 date-fns
          node pacman.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # Commit the generated SVG file
      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add pacman-contribution-animation.svg
          git commit -m "Update Pacman contribution animation" || echo "No changes to commit"
          git push
